### ISSUE TITLE
Why more accuracy from OSX's "Preview" application?

### ISSUE THREAD

**Issue by gbell12** [ianare/exif-py#47] opened 2015-02-07 07:21 UTC
For a particular image, exif-py tells me the latitude is:

EXIF GPS GPSLatitude, [31, 27, 2147/100]

So 31 degrees, 27 minutes, 21.47 seconds.  

But if I view the GPS info from Preview in OSX, it tells me 21.468 seconds.  An additional digit of accuracy.

Can you help me understand why?

Image and screenshot of exif-py and preview attached.

![why_more_accurate](https://cloud.githubusercontent.com/assets/3937658/6091248/fe3a4c54-aef5-11e4-8958-36b06d8b9816.jpg)
![img_0234](https://cloud.githubusercontent.com/assets/3937658/6091252/0c824ff0-aef6-11e4-8966-5aeb5f0dfc7f.JPG)

**Comment by ianare** [comment] 2015-02-09 13:36
Good question. I have to admit I'm not sure why that is...

I thought maybe it was using XMP information, but the file has none:

    > ~/work/oss/exif-py/EXIF.py -dc 0c824ff0-aef6-11e4-8966-5aeb5f0dfc7f.JPG
    ....
    DEBUG XMP not in Exif, searching file for XMP info ...
    DEBUG XMP Finished searching for info
    ....

I then checked with the popular exif tool and got the same result as with this library:

    > exif 0c824ff0-aef6-11e4-8966-5aeb5f0dfc7f.JPG
    EXIF tags in '0c824ff0-aef6-11e4-8966-5aeb5f0dfc7f.JPG' ('Motorola' byte order):
    .....
    Latitude            |31, 27, 21,47
    ....

**Comment by gbell12** [comment] 2015-02-13 06:31
Hmm... anything else I can do to help figure this out?  Would more photos help?

**Comment by ianare** [comment] 2015-02-14 10:30
What could be interesting is to compare an image not taken with Apple hardware and see if there is the same discrepency.

Maybe there is some sort of proprietary info not present in the Exif?

**Comment by jbest** [comment] 2015-08-12 16:35
Perhaps Preview is reading the same coordinate values, converting to decimal for internal manipulation, then converting back to DMS for the info panel display? That, along with some rounding and false precision might account for the discrepancy.

**Comment by spectras** [comment] 2015-09-04 19:34
Good point. For all we know, OSX's Preview could be the one reporting a wrong value.

**Comment by gbell12** [comment] 2015-09-04 23:51
It appeared to be more accurate for the photos I tested it with.

**Comment by spectras** [comment] 2015-09-05 02:17
The difference is 0.002", which is roughly 50cm.
But the best GPS receptors' accuracy is about 3 to 5 meters, which translates to 0.01" to 0.02".
So whatever the different software say, one thing is true for sure: the GPS receptor only provided at best 2-digit precision, so OSX Preview is wrong to display more than that.

Now, where it gets them from? My bet is it computes the latitude using decimal latitude. That is, it internally converts `[31, 27, 2147/100]` into a decimal number such as `31.4559639`. This is a very common thing to do, as having just one number for latitude is much more convenient than having an array of 4 numbers.

The problem is, such numbers cannot be perfectly represented as a decimals, let alone as floats. So, you just get an approximation. And when converting the value back into DMS for display, you will not get the original value back, just something really close to it. For instance,  `31° 27' 21.46839230493`. 

You then round it. Round it to 2 digits, you get `21.47`. Round it to 4 digits, you get `21.4684`, of which the last 2 digits actually are meaningless garbage.
=> Round it to 3 digits and you get `21.468`, that is `21.47` with a `-0.002` error caused by conversion approximations.

**Comment by ianare** [comment] 2015-09-07 19:48
Seems logical, I think we can close this one now. Thanks all.

**Closed by ianare** 2015-09-07 19:48 UTC
Labels: question
